### ISSUE TITLE
get current playback position ?

### ISSUE THREAD

**Issue by daslicht** [audiojs/web-audio-api#65]
Hi,
is it possible to get the current playback position when streaming to an ice cast server ? please?

~ Marc

**Comment by notthetup** [comment]
If you are using `AudioBufferSourceNode` then playback position isn't supported in original [WebAudio API](https://webaudio.github.io/web-audio-api/) itself.

**Comment by daslicht** [comment]
Thank you very much for the answer, do you know any solution how to get the playback position ?
That would be useful when dealing with meta and would allow us to broadcast position dependant things.

**Comment by dfcreative** [comment]
You can manually track `context.currentTime`

**Comment by notthetup** [comment]
`context.currentTime` may not be accurate, especially if `playbackRate` is being changed.

**Comment by daslicht** [comment]
That sounds awesome, I will do some tests !

Thank you very much !
