### ISSUE TITLE
Use automation-events to handle automation events in DspObject

### ISSUE THREAD

**Issue by chrisguttandin** [audiojs/web-audio-api#84]
I just noticed that there is some logic in the [`DspObject`](https://github.com/audiojs/web-audio-api/blob/master/lib/DspObject.js) class to maintain the automation events. I needed similar functionality for standardized-audio-context and standardized-audio-context-mock and therefore created a dedicated package to deal with that. It's called [automation-events](https://github.com/chrisguttandin/automation-events). Maybe it's worth using it here, too?

**Comment by dy** [comment]
Yeah, would be nice. Im not sure it will match the testcases here, if you can have a look.
